filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        remove_extra_empty_lines: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: true
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: true
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: undefined
                always: true
                else_on_new_line: false
            for:
                opening: undefined
                always: true
            while:
                opening: undefined
                always: true
            do_while:
                opening: undefined
                always: true
                while_on_new_line: false
            switch:
                opening: undefined
            try:
                opening: undefined
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

build:
    environment:
        php: 7.0.8
        java: java-8-oracle
        postgresql: false
        mongodb: false
        mysql: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false

    dependencies:
        before:
          - sudo apt-get install -y g++ make cmake libuv-dev libssl-dev libgmp-dev php5 php5-dev openssl libpcre3-dev git
          - echo "deb http://www.apache.org/dist/cassandra/debian 30x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
          - echo "deb-src http://www.apache.org/dist/cassandra/debian 30x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
          - gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D
          - gpg --export --armor F758CE318D77295D | sudo apt-key add -
          - gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00
          - gpg --export --armor 2B5C1B00 | sudo apt-key add -
          - gpg --keyserver pgp.mit.edu --recv-keys 0353B12C
          - gpg --export --armor 0353B12C | sudo apt-key add -
          - sudo apt-get update && sudo apt-get install -y cassandra
          - sudo pecl install cassandra

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
