language: php

php:
  - 5.6
  - 7
  - 7.1

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - oracle-java8-set-default

services:
  - cassandra

before_script:
  - sudo apt-get install -y g++ make cmake libuv-dev libssl-dev libgmp-dev php5 php5-dev openssl libpcre3-dev python-setuptools python-dev build-essential 
  - echo "deb http://www.apache.org/dist/cassandra/debian 30x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - echo "deb-src http://www.apache.org/dist/cassandra/debian 30x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install -y cassandra
  - cd /tmp && git clone https://github.com/datastax/cpp-driver.git && cd cpp-driver && git checkout 76656844bd13be1dbccbdb69dad93c2e9514e21f `#Version 2.6.0` && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install
  - sudo easy_install pip
  - pip install cqlsh
  - /usr/bin/cqlsh -f /home/scrutinizer/build/setup_cassandra_unittest_keyspace.cql

  - pecl install cassandra-1.2.2
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'php vendor/bin/coveralls -v'
